<?php //tlex/db/connectors
$r=[1=>['h1','h1','fr'],2=>['h2','h2','fr'],3=>['h3','h3','fr'],4=>['h4','h4','fr'],5=>['b','gras','fr'],6=>['i','italique','fr'],7=>['u','souligné','fr'],8=>['q','blockquote','fr'],9=>['--','ligne horizontale','fr'],10=>['br','saut de ligne','fr'],11=>['s','small','fr'],12=>['e','sup','fr'],13=>['n','sub','fr'],14=>['big','big','fr'],15=>['span','span','fr'],16=>['div','div','fr'],17=>['a','a href','fr'],18=>['url','lien url, affiche un lien réduit','fr'],19=>['web','prévisualisation web d\'une page, utilisant le protocole Open Graph (espace de nommage og: des métas)','fr'],20=>['img','image','fr'],21=>['tag','balise','fr'],22=>['ico','icône Fonteawesome','fr'],23=>['pic','picto Fontawesome utilisant le nommage FractaFramework','fr'],24=>['picto','picto Philum','fr'],25=>['lang','vocable dans la langue courante à partir de la référence FractaFramework','fr'],26=>['help','description dans la langue courante à partir de la référence FractaFramework','fr'],27=>['list','liste (lignes séparées par des doubles-lignes)','fr'],28=>['numlist','liste numérique (lignes séparées par des doubles-lignes)','fr'],29=>['table','tableau (colonnes séparées par des |, lignes séparées par des ¬)','fr'],30=>['form','Formulaire (,:;)

[input:name,
textarea:message,
select:choice:a;b;c,
checkbox:options:a;b,
radio:choose one:a;b,
bar:evaluation:form]','fr'],31=>['code','code source','fr'],32=>['art','(Tlex seulement) objet Article','fr'],33=>['artit','titre d\'un article','fr'],34=>['article','rendu d\'un article','fr'],35=>['app','ouvre une App dans une popup avec un paramètre (param, qui devient parfois id dans l\'App)','fr'],36=>['aj','appelle une séquence ajax (auth>3)','fr'],37=>['apj','ajoute une action ajax dans le header','fr'],38=>['popup','séquence ajax dans une popup','fr'],39=>['pagup','séquence ajax dans une pagup','fr'],40=>['imgup','image dans une pagup','fr'],41=>['no','n\'affiche pas le contenu du connecteur','fr'],42=>['on','affiche le contenu du connecteur sans l\'interpréter, par exemple un autre connecteur','fr'],43=>['video','vidéo (youtube, vimeo, daily) d\'après son ID','fr'],44=>['audio','lecteur audio (.mp3, .wav, etc...)','fr'],45=>['mp4','lecteur vidéo html5 (.mp4)','fr'],46=>['chat','module de discussion','fr'],47=>['gps','géolocalisation','fr'],48=>['open','ouvre une méthode d\'une classe (auth>6)','fr'],49=>['ascii','affiche un caractère ascii d\'après la partie alphanumérique de son identité (euro affich &#euro;)','fr'],50=>['id','(Tlex) contenu d\'un télex','fr'],51=>['red','texte en rouge','fr'],52=>['h','h3','fr'],53=>['h1','h1','en'],54=>['h2','h2','en'],55=>['h3','h3','en'],56=>['h4','h4','en'],57=>['b','bold','en'],58=>['i','italic','en'],59=>['u','underscore','en'],60=>['q','blockquote','en'],61=>['--','horizontal line','en'],62=>['br','line break','en'],63=>['small','small','en'],64=>['big','big','en'],65=>['sup','sup','en'],66=>['sub','sub','en'],67=>['span','span','en'],68=>['div','div','en'],69=>['a','a href','en'],70=>['url','lien url, affiche un lien réduit','en'],71=>['web','preview web page, using the protocol Open Graph (namespace og: metas)','en'],72=>['img','image','en'],73=>['tag','balise','en'],74=>['ico','icon Fonteawesome','en'],75=>['pic','picto Fontawesome utilisant le nommage FractaFramework','en'],76=>['picto','picto Philum','en'],77=>['lang','word in the current language from the ref of FractaFramework','en'],78=>['help','description in the current language from the ref of FractaFramework','en'],79=>['list','list (lines separated by double-lines)','en'],80=>['numlist','numeric list (lines separated by double-lines)','en'],81=>['table','table (columns separated by |, lines are separated by )','en'],82=>['form','Form (,:;)

[input:name,
textarea:message,
select:choice:a;b;c,
checkbox:options:a;b,
radio:choose one: (a;b,
bar:assessment:form]','en'],83=>['code','source code','en'],84=>['art','(Tlex only) object Article','en'],85=>['artit','title of an article','en'],86=>['article','report an article','en'],87=>['app','opens an App in a popup with a parameter (param, that sometimes becomes id in the App)','en'],88=>['aj','calls a sequence of ajax (auth>3)','en'],89=>['apj','adds a action ajax in the header','en'],90=>['popup','sequence ajax in a popup','en'],91=>['pagup','sequence ajax in a pagup','en'],92=>['imgup','image in a pagup','en'],93=>['no','does not display the contents of the connector','en'],94=>['on','displays the contents of the connector without interpreting it, for example another connector','en'],95=>['video','video (youtube, vimeo, daily) based on its ID','en'],96=>['audio','audio player (.mp3, .wav, etc...)','en'],97=>['mp4','html5 video player (.mp4)','en'],98=>['chat','module discussion','en'],99=>['gps','geolocation','en'],100=>['open','opens a class method (auth - >6)','en'],101=>['ascii','displays an ascii character according to the alphanumerical identity (euro vi &#euro;)','en'],102=>['id','(Tlex) content of a telex','en'],103=>['red','text in red','en'],104=>['h','h3','en'],105=>['h1','h1','es'],106=>['h2','h2','es'],107=>['h3','h3','es'],108=>['h4','h4','es'],109=>['b','grasa','es'],110=>['i','cursiva','es'],111=>['u','destacó','es'],112=>['q','blockquote','es'],113=>['--','la línea horizontal','es'],114=>['br','salto de línea','es'],115=>['small','small','es'],116=>['big','big','es'],117=>['sup','sup','es'],118=>['sub','sub','es'],119=>['span','span','es'],120=>['div','div','es'],121=>['a','a href','es'],122=>['url','url de enlace se muestra un enlace reduce','es'],123=>['web','vista previa de la página web, utilizando el protocolo Open Graph (espacio de nombres og: metas)','es'],124=>['img','imagen','es'],125=>['tag','etiqueta','es'],126=>['ico','icono de Fonteawesome','es'],127=>['pic','picto Fontawesome el uso de la nomenclatura FractaFramework','es'],128=>['picto','picto Philum','es'],129=>['lang','vocable dans la langue courante à partir de la référence FractaFramework','es'],130=>['help','descripción en el lenguaje corriente de la referencia FractaFramework','es'],131=>['list','lista (líneas separadas por doble líneas)','es'],132=>['numlist','lista numérica (líneas separadas por doble líneas)','es'],133=>['table','tabla (columnas separadas por |, las líneas están separadas por ¬)','es'],134=>['form','Formulaire (,:;)

[input:name,
textarea:message,
select:choice:a;b;c,
checkbox:options:a;b,
radio:choose one:a;b,
bar:evaluation:form]','es'],135=>['code','código fuente','es'],136=>['art','(Tlex sólo) objeto Artículo','es'],137=>['artit','el título de un artículo','es'],138=>['article','informe de un artículo','es'],139=>['app','Aplicación en una ventana emergente con un parámetro (param, que a veces se convierte en id en la Aplicación)','es'],140=>['aj','llama a una secuencia de ajax (auth>3)','es'],141=>['apj','agrega una acción ajax en el encabezado','es'],142=>['popup','secuencia de ajax en una ventana emergente','es'],143=>['pagup','secuencia de ajax en un pagup','es'],144=>['imgup','imagen en un pagup','es'],145=>['no','no muestra el contenido del conector','es'],146=>['on','muestra el contenido del conector, sin interpretar, por ejemplo, otro conector','es'],147=>['video','de vídeo (youtube, vimeo, daily) basado en su ID','es'],148=>['audio','lecteur audio (.mp3, .wav, etc...)','es'],149=>['mp4','lecteur vidéo html5 (.mp4)','es'],150=>['chat','module de discussion','es'],151=>['gps','geolocalización','es'],152=>['open','se abre un método de clase (auth - >6)','es'],153=>['ascii','muestra un carácter ascii de acuerdo con el alfanumérico de identidad (euro vi &#euro;)','es'],154=>['id','(Tlex) el contenido de un mensaje','es'],155=>['red','el texto en rojo','es'],156=>['h','h3','es'],157=>['k','texte barré','fr'],158=>['k','strike','en'],159=>['k','el texto tachado','es']];