<?php //tlex/db/help
$r=[1=>['ffw','Fractal','en'],2=>['decide_args','read and vote for the arguments','en'],3=>['txt_app','Datas are private and saved in your browser','en'],4=>['decide_app','Read, post and vote for the arguments of a decision to make.
1 - description of the decision
2 - create and vote of the arguments and counter-arguments
3 - discuss about each of them
An algorithm encrypts the validity of the decision between -100 and +100.','en'],5=>['decide_algo','The algorithm weighted the result of each argument by the number of clics.','en'],6=>['pray','Directed Meditation','en'],7=>['tabler_app','Converts an html table into reusable data','en'],8=>['poll_app','A survey is a form to multiple choice.','en'],9=>['desktop','Add icons to the Desktop','en'],10=>['desktop_modes','Types : nothing=popup, in=call app, lk=url','en'],11=>['art','Article','en'],12=>['genpswd','Password generator','en'],13=>['chat','Discussions','en'],14=>['desktop_auth','auth level required (after private level of App)','en'],15=>['model','App model','en'],16=>['biogen','biogenetic algorithm','en'],17=>['install','install sql tables','en'],18=>['connectors','Editor using software tags','en'],19=>['blockchains','successive transactions embellished with an algorithm; here used so as to impart the rules related industries','en'],20=>['tlex','💬 Tlex is a social network of objects. 
This is a Twitter-like which allows to use, relay and deploy Apps, which can send and receive information, such as content, chats, polls, votes, surveys, classifieds... And everything you can imagine !','en'],21=>['profile','profile','en'],22=>['article','compose an article','en'],23=>['tlex_nfo','This software is based on an open source architecture. It\'s don\'t make statistics and don\'t sell your mails.','en'],24=>['404error','This page doesn\'t exists','en'],25=>['private chat','This conversation is private','en'],26=>['404iderror','This user doesn\'t exists','en'],27=>['connhelp','[value*param:connector]','en'],28=>['404usrerror','This user doesn\'t exists','en'],29=>['soon','Open Soon !','en'],30=>['credits','[wrapper|art|id=59*About Tlex:aj] [wrapper|art|id=54*Functionality:aj] [wrapper|applist,tlex*List of Apps:aj] [wrapper|art|id=3*Légals:aj] [wrapper|art|id=4*Confidentiality:aj] [wrapper|art|id=5*Développers:aj] [wrapper|devnote*Notes of dev:aj] [wrapper|contact*Contact:aj] [wrapper|art|id=2*Credits:aj]','en'],31=>['recovery_mailsent','a mail has been sent','en'],32=>['welcome','[59:art]','en'],33=>['privacy_on','private mode : visible only by members','en'],34=>['privacy_off','public mode : visible for all','en'],35=>['form_filled','The form has been sent','en'],36=>['decide help','Edit the question and answers of your survey','en'],37=>['poll empty','poll is empty','en'],38=>['forms','Forms','en'],39=>['forms_com','set the fields like this :
type,label,option1/option2
a maximum of 8 fields','en'],40=>['form is not editable','Form is no longer editable','en'],41=>['petition','petition','en'],42=>['telex_reported','You have reported this telex as abusive','en'],43=>['petition_filled','You have signed this petition','en'],44=>['fontawesome','fontawesome.io','en'],45=>['decide','Rationale decision-making','en'],46=>['telex_banned','This telex have been reported as abusive','en'],47=>['vote_app','Majoritary ballot : evaluate each solution.
The winner is the solution which have obtained 50% of votes for the best value.','en'],48=>['map','GPS / Maps','en'],49=>['tabler','Table','en'],50=>['poll','Question with choices','en'],51=>['slide','Slides','en'],52=>['vote','Majority judgment','en'],53=>['message posted','Your message was posted','en'],54=>['oAuth','automatic authentification given in profile','en'],55=>['message not posted','The message was not posted','en'],56=>['no results','No results','en'],57=>['apisql','receipt mysql datas','en'],58=>['barter_app','Sale, Give, Exchange goods and services','en'],59=>['subscribe approved','subscription approved','en'],60=>['private account','This account is private','en'],61=>['empty_home','No telex published','en'],62=>['notif_like','has liked your message','en'],63=>['notif_follow','is now following','en'],64=>['devnote','Notes of dev','en'],65=>['tlex_remove_account','Account Removal Procedure:
- you will no longer have any subscribers
- your account will be made private (and invisible to the public)','en'],66=>['account disactivated','Your account is now disactivated','en'],67=>['twitterApi','The Twiiter Api allows you to tweet directly from Tlex. More infos: https://apps.twitter.com','en'],68=>['admin_twitter','manage oAuths of Twitter','en'],69=>['twit sent','The Tweet has been sent','en'],70=>['error','An error occured','en'],71=>['sticker_app','Allows you to create a poster html','en'],72=>['meet_help','Set and participate to rendez-vous','en'],73=>['meet','Rendez-Vous','en'],74=>['notifs_on','Receive notiications by mail','en'],75=>['notifs_off','Do not receive notifications by mail','en'],76=>['notif_reply','has reply','en'],77=>['notif_quote','has quoted your message','en'],78=>['notif_subscr','is now following you','en'],79=>['notif_chat','sent you a private message','en'],80=>['pray_edit','Decide what you want to ask at the group level.

Write it in a simple text of moderate length, with short sentences.

Memorize this text, with a full understanding of each application.

Each day for a week, each in the group must PRAY this text at the same time (IMPORTANT).

It is not necessary to do this by grouping yourself physically, but you will coordinate the entire group to ensure that each member is available to join the prayer at the same time.','en'],81=>['pray_how','Choose a deceased person for whom you had an intense tenderness (mother, father, grandparents, sincere friend ...). You can choose a different person from one day to the next. Some of your brothers systematically choose the archetypal image of Christ (Jesus) with whom they had no interaction during their lives. This is NOT effective, unless it bears true and intense devotion.

You have to observe a silence of 6 to 7 minutes to concentrate before asking, focusing deeply on that person, imagining that she is looking at you and is ready to listen to you.

Recite the text mentally, pronouncing the words slowly and clearly. Try to pronounce your sentences with a strong mental voice, as if you telepathically communicate with the deceased (this is an image, we hope you will understand the meaning).

You must have a true belief in the importance of your request because it is \"heard\" exactly how it is expressed. You must adopt the modest and humble posture of a suppliant asking a huge favor to the only person able to grant it to you.

You must finally observe the silence for 6 to 7 minutes, concentrating after the prayer by thanking and taking leave of the deceased.

You must repeat this prayer every day for seven consecutive days (no more, no less). It should not last more than twenty minutes every day.','en'],82=>['need auth','Required permission level','en'],83=>['model_app','Model App to decline
uses 2 columns, tit and txt
uses all the devices basic','en'],84=>['imgtxt','Image-text','en'],85=>['pad_app','html editor, datas are saved in the LocalVars of your browser','en'],86=>['urgency','Alert message','en'],87=>['closed account','Closed account','en'],88=>['slide_app','It is a system that allows you to make short presentations in text format. The small originality is that these slides can form a topological tree.','en'],89=>['gps_app','The geolocation module uses Open Data data from the French government, and OpenStreetMap mapping.
It is possible to specify a place from a search.','en'],90=>['chat_app','The chat rooms allow users to chat instantly, and isolated. 
The rooms can be private or public, in which case you can receive guests.','en'],91=>['petition_app','Petitions are forms that collect membership through an accreditation. Signing a petition on a network like Tlex is made extremely simple.','en'],92=>['forms_app','Allows you to create a form containing text fields, selection lists, radio buttons, checkboxes, or evaluation bars.','en'],93=>['pray_app','Add guided meditation sessions, specifying the start date.
Participants report their presence on the calendar.
There must be 7 participants per day, for 7 consecutive days, for the prayer to be heard.','en'],94=>['meet_app','Organize appointments by specifying an address (which returns a Map) and a date. Participants can register and report their attendance.','en'],95=>['urgency_app','Allows you to create messages using the graphic of \"Smoking Kills\"','en'],96=>['card','Business card','en'],97=>['card_app','Compose your visit card','en'],98=>['vote empty','No choice was offered','en'],99=>['art_app','Editor that allows you to compose an article
Supports both the html that the [connectors].
To enter the quick edit, double-click on the text box.','en'],100=>['article not exists','This article does not exists','en'],101=>['map_app','Mapping using OpenStreetMap','en'],102=>['tickets_app','Make proposals, remarks, suggestions for improvement in relation to the software Tlex.
The posts are visible by all.','en'],103=>['convert_app','Format converter data','en'],104=>['operation not permited','operation not permited','en'],105=>['download_app','Tlex is Open Source !You can view / use / improve the code / use it in education !
under the terms of GPLv3 ','en'],106=>['download_app','Tlex is Open Source !
You can view / use / improve the code / use it in education !
under the terms of GPLv3 ','en'],107=>['loged_needed','You need to be loged to do that','en'],108=>['no element','No elements','en'],109=>['no app loaded','This App does not exist','en'],110=>['chat not exists','This discussion does not exist','en'],111=>['public documents','The public documents can be shared with other users','en'],112=>['note_app','Note is that the app is a minimum, with just a text field, which accepts the connectors','en'],113=>['note','Simple text','en'],114=>['purpose_app','Allows you to propose ideas of how multilingual, en, en, and es. The translation is automatic.
Only the elements in your language appear.','en'],115=>['tickets','Suggestions','en'],116=>['petition closed','The petition is finished','en'],117=>['form closed','The form is closed','en'],118=>['need auth 2','You must be logged in','en'],119=>['need auth 1','You must be logged in','en'],120=>['need auth 3','You must have a special authorization (3)','en'],121=>['need auth 4','You must have a permission level of editor (4)','en'],122=>['need auth 5','You must have a permission level of responsibility (level 5)','en'],123=>['need auth 6','You must have a permission level of Admin (level 6)','en'],124=>['need auth 7','You must be a superadmin (level 7)','en'],125=>['id not exists','This document no longer exists','en'],126=>['purpose','Multilingual sharing','en'],127=>['tlex_donations','Tlex is a project.
We need you to continue !','en'],128=>['loto','Lottery solidarity','en'],129=>['loto_app','Invest the credits in the lottery of solidarity,
- the winners share 50% of the winnings
- the account that launched the lottery wins the other 50%','en'],130=>['book','Book','en'],131=>['book_app','Write a book by publishing a chapter per day','en'],132=>['sticker_edit','[text,size,color,x/y,angle]
ex: 
hello,36,ff0000,180/300,10
hello,36,red,center/top,-10','en'],133=>['vector_edit','Utilise les connecteurs SVG ([10,10,30,20:rect])
voir /app/_svg','en'],134=>['vector_app','Draw vector graphics using the connectors SVG','en'],135=>['vector','Vector drawing','en'],136=>['code','Source Code','en'],137=>['code_app','Syntax highlighting','en'],138=>['imgtxt_app','Tool to create text in image format','en'],139=>['sticker','Sticker','en'],140=>['new password saved','New password saved','en'],141=>['poster_app','Allows you to write text on images','en'],142=>['poster','Displays','en'],143=>['voting_app','In an election, enter the results of your electoral district, identified by its postal code, in order to compare these results with other.','en'],144=>['voting','Vigilant citizen','en'],145=>['voting','Vigilant citizen','en'],146=>['thank you','Thank you','en'],147=>['bank','Bank','en'],148=>['bank_app','Accounts-credit rights.
Create a credit added to your account once validated by a third party (when it commits the transaction).
The transactions are of three types :
- products (currency red)
- work (mint blue)
- resource (mint green)

At the opening of the account, the credits you have available.
Your income and your expenses may be expressed in credits red.
They depend on your contribution to the system, recorded through the credits blue and green.

The currency transactions green (resources) must be validated by a committee, which ensures that they are used to best advantage.','en'],149=>['confidentiality','This site is based on an architecture that is Open Source.
Your activity on the site is not being stalked.
No commercial activity takes place with your data.
Your data is de facto published without a license.
Users are responsible for their publications.
Tlex disclaims any liability with regard to the use of data or software.','en'],150=>['no_extension','do not specify the file extension','en'],151=>['artwork','Binding','en'],152=>['artwork_app','Connect all of the items of Art to make a book','en']];