<?php
//tlex/db/help
$r=[1=>['ffw','Fractal','fr'],2=>['decide_args','Votez pour ou contre les arguments positifs ou négatifs d\'une décision.
Créez des argumentaires et faites-les voter.','fr'],3=>['txt_app','Les données sont privées et enregistrées en local sur votre navigateur','fr'],4=>['decide_app','Lire, poster et voter pour les arguments d\'une décision à prendre.
1 - description de la décision
2 - créer et voter des arguments et contre-arguments
3 - discuter à propos de chacun d\'eux
Un algorithme chiffre la validité de la décision entre -100 et +100.','fr'],5=>['decide_algo','L\'algorithme pondère le résultat de chaque argument par le nombre de clics.','fr'],6=>['pray','Méditation dirigée','fr'],7=>['notifs_on','Recevoir les notifications par mail','fr'],8=>['meet_help','Fixez et signalez votre participation à des rendez-vous','fr'],9=>['tabler_app','Convertit un tableau html en données réutilisables','fr'],10=>['poll_app','Un sondage est un formulaire à choix multiples.','fr'],11=>['need auth 2','Vous devez être logué','fr'],12=>['desktop','Edition des icônes du Desktop','fr'],13=>['art','Article','fr'],14=>['desktop_modes','vide = appelle une App
lk = url
j = full com
pop, pag, img','fr'],15=>['genpswd','Générateur de mot de passe','fr'],16=>['chat','Discussions','fr'],17=>['desktop_auth','niveau de permission requis (subordonné au param private de l\'App)','fr'],18=>['model','modèle d\'App','fr'],19=>['biogen','algorithme biogénétique','fr'],20=>['install','installation des tables sql','fr'],21=>['connectors','Editeur utilisant des balises logicielles','fr'],22=>['blockchains','transactions successives agrémentées d\'un algorithme ; utilisé ici de façon à conférer des règles liées aux secteurs d\'activité','fr'],23=>['tlex','💬 Tlex est un réseau social d\'objets. 
C\'est un Twitter-like qui permet d\'utiliser, relayer et déployer des Apps, qui peuvent envoyer et recevoir des informations, telles que des contenus, des chats, scrutins, votes, sondages, petites annonces... Et tout ce que vous pouvez imaginer !','fr'],24=>['404error','Cette page n\'existe pas','fr'],25=>['tlex_nfo','Ce site repose sur une architecture open source. Il ne récolte aucune données ou statistiques, et ne revend pas vos mails.','fr'],26=>['article','Article','fr'],27=>['profile','profile','fr'],28=>['tlex_nfo','@2017 Logiciel écrit sous Fractal','fr'],29=>['connhelp','[content*option:connector]','fr'],30=>['404iderror','Cet ID n\'existe pas','fr'],31=>['404usrerror','Cet utilisateur n\'existe pas','fr'],32=>['soon','Ouverture prochaine du site','fr'],33=>['credits','[wrapper|art|id=6*Bienvenue:aj] [wrapper|art|id=54*Fonctionnalités:aj] [wrapper|applist,tlex*Liste des Apps:aj] [wrapper|art|id=3*Mentions légales:aj] [wrapper|art|id=4*Confidentialité:aj] [wrapper|art|id=5*Développeurs:aj] [wrapper|devnote*Notes de dev:aj] [wrapper|contact*Contact:aj] [wrapper|art|id=2*Crédits:aj]','fr'],34=>['fontawesome','fontawesome.io','fr'],35=>['decide','Argumentaire décisionnel','fr'],36=>['decide help','Editez la question et les réponses de votre sondage','fr'],37=>['no results','Aucun résultat','fr'],38=>['recovery_mailsent','Un e-mail vous a été envoyé','fr'],39=>['welcome','[6:art]','fr'],40=>['privacy_on','mode privé : visible uniquement par les abonnés','fr'],41=>['privacy_off','mode public : visible par tout le monde','fr'],42=>['poll empty','Le questionnaire est incomplet','fr'],43=>['forms','Formulaires','fr'],44=>['forms_com','définir les champs comme ceci :
type,label,option1/option2
maximum 8 champs','fr'],45=>['form is not editable','le formulaire n\'est plus éditable','fr'],46=>['form_filled','Le formulaire a été envoyé','fr'],47=>['petition','Pétition','fr'],48=>['telex_reported','Vous avez signalé ce télex comme abusif','fr'],49=>['petition_filled','Vous avez signé la pétition','fr'],50=>['telex_banned','Ce télex a été reporté comme abusif','fr'],51=>['vote_app','Votez en donnant une note à chacune des propositions.
Le gagnant est celui dont 50% des votants donnent les meilleures appréciations.','fr'],52=>['tabler','Tableaux','fr'],53=>['poll','Sondage','fr'],54=>['slide','Diapositives','fr'],55=>['vote','Scrutin majoritaire','fr'],56=>['message posted','Votre message a été envoyé','fr'],57=>['message not posted','Le message n\'a pas été envoyé','fr'],58=>['oAuth','authentification automatique fournie dans le profile','fr'],59=>['apisql','acquisition de données mysql','fr'],60=>['barter_app','Vendre, donner, échanger des biens et services','fr'],61=>['subscribe approved','inscription approuvée','fr'],62=>['private account','Ce compte est privé.','fr'],63=>['empty_home','Aucun télex publié.','fr'],64=>['notif_like','a aimé votre message','fr'],65=>['notif_follow','s\'est abonné','fr'],66=>['devnote','Notes de dev','fr'],67=>['tlex_remove_account','Procédure de suppression de compte : 
- vous n\'aurez plus aucun abonné
- votre compte sera rendu privé (et invisible au public)','fr'],68=>['account disactivated','Le compte a été désactivé','fr'],69=>['twitterApi','l\'Api permet d\'interagir avec votre compte Twitter. 
Plus d\'infos : https://apps.twitter.com','fr'],70=>['admin_twitter','Admin des oAuths de Twitter','fr'],71=>['twit sent','Le Tweet a été envoyé','fr'],72=>['error','Une erreur est survenue','fr'],73=>['sticker_app','Permet de créer une affiche html','fr'],74=>['meet','Rendez-Vous','fr'],75=>['notifs_off','Ne pas recevoir les notifications par mail','fr'],76=>['notif_reply','a répondu','fr'],77=>['notif_quote','a cité votre message','fr'],78=>['notif_subscr','s\'est abonné','fr'],79=>['notif_chat','vous a envoyé un message privé','fr'],80=>['pray_edit','Décidez de ce que vous voulez demander, au niveau du groupe.

Ecrivez-le dans un texte simple d\'une longueur modérée, avec des phrases courtes.

Mémorisez ce texte, avec une complète compréhension de chaque demande.

Chaque jour pendant une semaine, chacun dans le groupe doit PRIER ce texte au même moment (IMPORTANT).

Il n\'est pas nécessaire de le faire en se groupant physiquement, mais vous coordonnerez le groupe entier pour vous assurer que chaque membre est disponible pour joindre la prière en même temps.','fr'],81=>['pray_how','Choisissez une personne décédée pour laquelle vous aviez une intense tendresse (mère, père, grands-parents, ami sincère). Vous pouvez choisir une personne différente d\'un jour sur l\'autre. Quelques uns de vos frères choisissent systématiquement l\'image archétypale du Christ (Jésus) avec lequel il n\'ont eu aucune interaction pendant leur vie. Ce n\'est PAS efficace, à moins de lui porter une véritable et intense dévotion.

Vous devez observer un silence de 6 à 7 minutes pour vous concentrer avant de demander, en vous focalisant profondément sur cette personne, imaginant qu\'elle vous regarde et qu\'elle est prête à vous écouter.

Récitez le texte mentalement, en prononçant les mots lentement et clairement. Essayer de prononcer vos phrases avec une voix mentale forte, comme si vous communiquiez télépathiquement avec la personne décédée (c\'est une image, nous espérons que vous comprendrez la signification).

Vous devez avoir une véritable croyance dans l\'importance de votre requête parce qu\'elle est \"entendue\" exactement de la façon dont elle est exprimée. Vous devez adopter la posture modeste et humble d\'un suppliant demandant un faveur énorme à la seule personne capable de vous l\'accorder.

Vous devez finalement observer le silence pendant 6 à 7 minutes, vous concentrant après la prière en remerciant et en prenant congé de la personne décédée.

Vous devez répéter cette prière chaque jour pendant sept jours consécutifs (ni plus, ni moins). Ça ne devrait pas durer plus de vingt minutes quotidiennement.','fr'],82=>['model_app','Modèle d\'App à décliner
utilise 2 colonnes, tit et txt
utilise tous les dispositifs basiques','fr'],83=>['imgtxt','Image-texte','fr'],84=>['sticker','Autocollant','fr'],85=>['pad_app','Editeur html.
Vos données sont enregistrées dans les localvars de votre navigateur.','fr'],86=>['private chat','Cette conversation est privée','fr'],87=>['urgency','Messages d\'alerte','fr'],88=>['closed account','Compte fermé','fr'],89=>['chat_app','Les salles de discussion permettent aux utilisateurs de discuter de manière instantanée et isolée. 
Les salles peuvent être privées ou publiques, auquel cas vous pouvez recevoir des invités.','fr'],90=>['gps_app','Le module de géolocalisation fait appel aux données Open Data du gouvernement français, et à la cartographie OpenStreetMap.
Il est possible de spécifier un lieu issu d\'une recherche.','fr'],91=>['slide_app','C\'est un système qui permet de faire des présentations courtes au format texte. La petite originalité est que ces diapositives peuvent former un arbre topologique.','fr'],92=>['petition_app','Les pétitions sont des formulaires qui récoltent des adhésions via un agrément. Le fait de signer une pétition sur un réseau tel que Tlex est rendu extrêmement simple.','fr'],93=>['forms_app','Permet de créer un formulaire contenant des champs texte, des listes de choix, des boutons radio, des cases à cocher, ou encore des barres d\'évaluation.','fr'],94=>['pray_app','Ajoutez des séances de méditation dirigée, en précisant la date de début.
Les participants signalent leur présence dans le calendrier.
Il doit y avoir 7 participants par jour, pendant 7 jours consécutifs, pour que la prière soit entendue.','fr'],95=>['meet_app','Organisez des rendez-vous en spécifiant une adresse (qui renvoie une Map) et une date. Les participants peuvent s\'inscrire et signaler leur présence.','fr'],96=>['urgency_app','Permet de créer des messages en utilisant le graphisme de \"Fumer tue\"','fr'],97=>['card','Carte de visite','fr'],98=>['card_app','Composer une carte de visite','fr'],99=>['vote empty','Aucun choix n\'a été proposé','fr'],100=>['art_app','Editeur qui permet de composer un article.
Supporte aussi bien le html que les [connecteurs].
Pour entrer dans l\'édition, double-cliquez sur la zone de texte.','fr'],101=>['map','GPS / Cartes','fr'],102=>['article not exists','Cet article n\'existe pas','fr'],103=>['map_app','Cartographie utilisant OpenStreetMap','fr'],104=>['convert_app','Convertisseur de formats de données','fr'],105=>['tickets_app','Faites des propositions, remarques, suggestions d\'amélioration à propos du logiciel Tlex.
Les posts sont visibles par tous.','fr'],106=>['operation not permited','opération interdite','fr'],107=>['download_app','Tlex est Open Source !
Vous pouvez consulter / utiliser / améliorer le code / l\'utiliser dans l\'éducation !
sous les conditions de GPLv3+','fr'],108=>['loged_needed','Vous devez être identifié pour faire cela','fr'],109=>['no element','Aucun élément','fr'],110=>['need auth','Niveau d\'autorisation requis','fr'],111=>['no app loaded','Cette App n\'existe pas','fr'],112=>['chat not exists','Cette discussion n\'existe pas','fr'],113=>['purpose_app','Permet de proposer des idées de façon multilingue, en fr, en et es. La traduction est automatique.
Seuls les éléments dans votre langue apparaissent.','fr'],114=>['public documents','Les documents publics peuvent être partagés avec les autres utilisateurs','fr'],115=>['note_app','Note est une app minimale, avec juste un champ texte, qui accepte les connecteurs','fr'],116=>['note','Texte simple','fr'],117=>['tickets','Suggestions','fr'],118=>['petition closed','La pétition est terminée','fr'],119=>['sticker_edit','[text,size,color,x/y,angle]
ex: 
hello,36,ff0000,180/300,10
hello,36,red,center/top,-10','fr'],120=>['id not exists','Ce document n\'existe plus','fr'],121=>['need auth 1','Vous devez être logué','fr'],122=>['form closed','Le formulaire est fermé','fr'],123=>['need auth 3','Vous devez avoir un niveau d\'autorisation spécial (3)','fr'],124=>['need auth 4','Vous devez avoir un niveau d\'autorisation d\'éditeur (4)','fr'],125=>['need auth 5','Vous devez avoir un niveau d\'autorisation de responsable (niveau 5)','fr'],126=>['need auth 6','Vous devez avoir un niveau d\'autorisation d\'Admin (niveau 6)','fr'],127=>['need auth 7','Vous devez être superadmin (niveau 7)','fr'],128=>['purpose','Partage multilingue','fr'],129=>['tlex_donations','Tlex est un projet.
Nous avons besoin de vous pour continuer !','fr'],130=>['loto','Loterie solidaire','fr'],131=>['loto_app','Investissez des crédits dans cette loterie solidaire,
- les gagnants se partagent 50% des gains
- le compte ayant lancé la loterie gagne les autres 50%','fr'],132=>['book','Livre','fr'],133=>['book_app','Écrivez un livre en publiant un chapitre par jour','fr'],134=>['imgtxt_app','Outil de création de texte au format image','fr'],135=>['vector_edit','Utilise les connecteurs SVG ([10,10,30,20:rect])
voir /app/_svg','fr'],136=>['vector','Dessin vectoriel','fr'],137=>['vector_app','Dessinez des graphiques vectoriels en utilisant les connecteurs SVG','fr'],138=>['code','Code source','fr'],139=>['code_app','Coloration syntaxique','fr'],140=>['new password saved','Nouveau mot de passe enregistré','fr'],141=>['poster','Affiche','fr'],142=>['poster_app','Permet d\'écrire du texte sur des images','fr'],143=>['voting','Vigilance citoyenne','fr'],144=>['voting_app','Lors d\'une élection, rentrez les résultats de votre circonscription, identifiée par son code postal, afin de comparer ensuite ces résultats avec d\'autres.','fr'],145=>['thank you','Merci','fr'],146=>['bank','Banque','fr'],147=>['bank_app','Comptes des crédits-droits.
Créer un crédit ne l\'ajoute à votre compte qu\'une fois validé par un tiers (lorsqu\'il valide la transaction).
Les transactions sont de trois types :
- produits (monnaie rouge)
- travail (monnaie bleue)
- ressource (monnaie verte)

A l\'ouverture du compte, des crédits vous ont offerts.
Vos revenus et dépenses ne s\'expriment qu\'en crédits rouges.
Ils dépendent de votre contribution au système, comptabilisée via les crédits bleus et verts.

Les transactions en monnaie verte (ressources) doivent être validées par un comité, qui s\'assure qu\'elles sont employées au mieux.','fr'],148=>['confidentiality','Ce site repose sur une architecture Open Source.
Votre activité sur le site n\'est pas traquée.
Aucune activité commerciale n\'a lieu avec vos données.
Vos données sont de facto publiées sans licence.
Les utilisateurs sont responsables de leurs publications.
Tlex décline toute responsabilité quant à l\'usage des données ou du logiciel.','fr'],149=>['no_extension','ne pas spécifier l\'extension de fichier','fr'],150=>['artwork','Reliure','fr'],151=>['artwork_app','Reliez ensemble des articles de Arts pour en faire un livre','fr']];
?>